### ISSUE TITLE
Server required node > 8.1

### ISSUE THREAD

**Issue by deewhyweb** [aerogear/ionic-showcase#150]
The server fails to run with node version 6.x as stated in the documentation due to the use of async functions.  Version 8.1 or above is required.
Happy to push a PR with an update to the readme

/Users/philiphayes/projects/ionic-showcase/server/src/index.js:32
async function start() {
      ^^^^^^^^
SyntaxError: Unexpected token function

**Comment by wtrocki** [comment]
We will be always supporting latest LTS for showcase. Node 12 LTS is going to be released in 2 weeks.

**Comment by wtrocki** [comment]
Tried and tested on latest node. Updated docs
