### ISSUE TITLE
Unable to build latest master

### ISSUE THREAD

**Issue by evanshortiss** [aerogear/ionic-showcase#219]
## Bug Report

* **Version/Commit**: 23b14f351ba6395ad08cd261b5cef9210ebfa611
* **Ionic Version**: 4 (that's what is specified in README)
* **Node.js / npm versions**: 10.15

I tried to build the application like so:

```
npm i ionic@4 cordova -g
ionic cordova platform add android
ionic cordova build android
```

It fails with the error:

```
> ng run app:ionic-cordova-build --platform=android
Schema validation failed with the following errors:
  Data path ".builders['cordova-build']" should have required property 'class'.
[ERROR] An error occurred while running subprocess ng.
        
        ng run app:ionic-cordova-build --platform=android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

It seems others have this issue [here](https://github.com/ionic-team/angular-toolkit/issues/166)

Should this repository include `cordova` and `ionic` versions in the package.json to avoid such issues?

**Comment by wtrocki** [comment]
Yes. I have noticed that today and working to address it. Using one of the ionic showcase releases should be ok. Going to fix problem as soon as possible

**Comment by evanshortiss** [comment]
Thanks @wtrocki, using older tags worked. I will close this since you are aware and probably have it fixed by now based on our chat 😄

**Comment by wtrocki** [comment]
New release is available now. Master should work as well
