### ISSUE TITLE
several issues with demo example when setting up on mac os

### ISSUE THREAD

**Issue by cjohn001** [aerogear/ionic-showcase#284]
Hello together, 
I am currently trying to setup this example on my mac. Unfortunately without  much success so far. There were several issues I ran into:

1. When I follow the readme to set up the demo and I try to enable keycloak support

```
npm run keycloak:init

> server-apollo@1.0.0 keycloak:init /Users/cjohn/Entwicklung/IMS_Help/ionic-showcase/server
> node ./scripts/keycloak/initKeycloak.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/cjohn/Entwicklung/IMS_Help/ionic-showcase/server/scripts/keycloak/initKeycloak.js:14:15)
```

I got the above error message. Seems like there was a dependency to axios missing. I could install it manually and than the script worked.

2. When the keycloak init script finishes it provides the configuration files for the graphql server and the client app. 

```
2. Copy the following app config into the auth section in ionic-showcase/assets/config.js
{
  "id": "some-id",
  "name": "keycloak",
  "type": "keycloak",
  "url": "http://localhost:8080/auth",
  "config": {
    "realm": "voyager-testing",
    "auth-server-url": "http://localhost:8080/auth",
    "ssl-required": "none",
    "resource": "voyager-testing-public",
    "public-client": true,
    "use-resource-role-mappings": true,
    "confidential-port": 0
  }
}
```
The file ionic-showcase/assets/config.js does not exist in the project. I assume the relevant file is under 
ionic-showcase/src/assets/config/config.js
At least I added the configuration into this file in the following way:

```
window.showcaseConfig = {
  "backend": {
    "serverUrl": "http://localhost:4000/graphql",
    "wsServerUrl": "ws://localhost:4000/graphql"
  },
  // "push": {},
  "auth": {
	"id": "some-id",
  	"name": "keycloak",
  	"type": "keycloak",
  	"url": "http://localhost:8080/auth",
  	"config": {
    		"realm": "voyager-testing",
    		"auth-server-url": "http://localhost:8080/auth",
    		"ssl-required": "none",
    		"resource": "voyager-testing-public",
    		"public-client": true,
    		"use-resource-role-mappings": true,
    		"confidential-port": 0
  	}
  }
};
```

Unfortunately, the client configuration does not seem to work for me. Please note, I also copied the configuration file into the specified location ionic-showcase/assets/config.js. This did not work either. When using the client app in my browser no functionality in the demo is working:

- When I go to manage tasks it says "online" I assume there exists a connection to graphql server? However, I also get the following error message "Problem with listening to cache changes" And I am not able to add task via the + submenu.

- When I go to User Profile, I get the following error message: "Login failed. Cannot retrieve profile.Please review keycloak client configuration

- Files, When I go into this section I also get an error message: Fetching Files. Cannot fetch files. Please make sure you are online.

- Under Settings I can enable push. However, from the description it is unclear to me if I need an additional server to run push notifications and how this feature can be used in the demo. Is the Mosca MQTT Broker used for this functionality?

I assume my interpretation of the config file is somehow wrong. Could you please give me directions on how I could get this demo up and running and please improve the documentation.
Thanks!

Please note, adding tasks in online and offline mode works as expected if I disable the keycloak integration. So this seems to be the reason. Hence, I assume I would need to hints from you. Where to put the config and how to use the push functionality
Best regards,
 Christoph

**Comment by wtrocki** [comment]
@cjohn001 Amazing issue! thank you so much for logging it with so many useful details. 
I have fixed all issues and they should be available on a master branch now. 
Really sorry for issues that you were experiencing. 

PS: We also have guided documentation that is using showcase:
https://github.com/aerogear/mobile-walkthrough/

If you are looking to deploy Showcase see also:
https://github.com/aerogear/datasync-deployment
