### ISSUE TITLE
Documentation seems to be wrong in order to use showcase app with keycloak

### ISSUE THREAD

**Issue by cjohn001** [aerogear/ionic-showcase#293]
I started and configured keycloak, the server and the app according to the descriptions in the README.
When starting the server I get the following output:

```
warning: couldn't find config at /Users/cjohn/Entwicklung/IMS_Help/ionic-showcase/server/src/config/push-config.json
Using MQTT PubSub
attempting to connect to messaging service localhost
Initializing Keycloak authentication
connected to messaging service

    ***********************************************************
    🎮 Ionic PWA application available at http://localhost:4000
    🚀 GraphQL Playground is available at http://localhost:4000/graphql
    ***********************************************************
```

when trying to open playground via http://localhost:4000/graphql
I only get an access denied message.

Note: I cannot follow the playground configuration following the documentation section
==== Using the GraphQL playground with Keycloak

As I cannot open the playground at all. Could be please describe how I can use username,password to open the playground?

**Comment by wtrocki** [comment]
Hi

It looks like master got broken with some recent changes. We have done testing for keycloak recently on https://github.com/aerogear/ionic-showcase/pull/288

If you use that commit all should work. Our team will try to investigate this issue and revert breaking changes.

CC @darahayes @kingsleyzissou

**Comment by cjohn001** [comment]
Hello wtrocki,
can you tell me how I can switch to #288? Thanks. Seems I have no option here to download an older untagged version.

**Comment by wtrocki** [comment]
Please try master. I have reverted changes.

**Comment by cjohn001** [comment]
@wtrocki 
Hello,
unfortunately the new master also does not work for me. When visiting http://localhost:4000/graphql I still get Access denied.

I followed the following path
- fresh clone
- cd server
- npm install
- docker-compose up
- from server folder, npm run keycloak (note, I assume there is a bug in the docs. It says cd keycloak but there is no folder keycloak)
- from server folder npm run keycloak:init
- setup of configuration, where I followed:
```
1. Copy the following app config into the auth section in ionic-showcase/src/assets/config/config.js

window.showcaseConfig = {
  ...
{
  "auth": {
    "url": "http://localhost:8080/auth",
    "realm": "voyager-testing",
    "clientId": "voyager-testing-public"
  }
}
  ...
}

2. Copy the following server config into ionic-showcase/server/src/config/keycloak.json

{
  "realm": "voyager-testing",
  "bearer-only": true,
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "none",
  "resource": "voyager-testing-bearer",
  "use-resource-role-mappings": true,
  "confidential-port": 0
}
```
- in folder server: npm run dev

- folllowed link given in console http://localhost:4000/graphql

Please let me know if something is wrong with this procedure. I am using the sources on a Mac.

**Comment by wtrocki** [comment]
Can we try incognito mode in browser? We should get redirect to keycloak login page. Also your browser console log would help us to see what is happening

**Comment by cjohn001** [comment]
@wtrocki 
I tried in incognito mode, but the result is the same. I also do not get any messages in console log in chrome dev tools.

<img width="1484" alt="Bildschirmfoto 2020-01-26 um 19 06 58" src="https://user-images.githubusercontent.com/43253483/73139554-664b9b80-406f-11ea-8a28-8714d4d7a384.png">

**Comment by wtrocki** [comment]
Ok. I see what is the issue. 
Showcase works in two modes:

- Development mode with autoreload. 
It is possible to configure keycloak for development mode, however 
Following this guide will keep both clietn and server app secured by keycloak:
https://github.com/aerogear/ionic-showcase/#running-the-server-with-the-keycloak-integration

However, Guide for the playground will not work as server and client running using different ports in this mode.

https://github.com/aerogear/ionic-showcase/#using-the-graphql-playground-with-keycloak

- Client build and being served by server. In this scenario running npm build will build client

**Comment by wtrocki** [comment]
If the playground is required we can use any playground outside the server that will connect with the server

**Comment by cjohn001** [comment]
Hello,
I unfortunately cannot follow your descriptions. So is there a way to get local server development with keycloak and playground working? Would be very difficult to develop without, By the way, I used npm run dev not npm run start, but I assume except mqtt running on localhost it should be the same.

>>If the playground is required we can use any playground running outside the server that will connect to the server URL and pass the token

You mean it should not run on the same machine?

**Comment by wtrocki** [comment]
I mean that you can run any graphql client. For example https://altair.sirmuel.design outside the app and simply connect to server.

**Comment by cjohn001** [comment]
I do have things running on my local computer not a public server. Is there no way to get a local dev setup? 
I worked with keycloak before and do not understand your first point completely. There is not a thing like dev mode for keycloak as far as I know.

Is the problem that the keycloak user login and the playground client would need to run on the same port? Is it possible to configure keycloak or playground to use a different port than and change forwording somehow?

**Comment by wtrocki** [comment]
We got small misunderstanding so going back to basics.

I have tried couple times instruction for running keycloak showcase server and showcase app (they are different app processes).
Please follow instructions here:
https://github.com/aerogear/ionic-showcase/#running-the-server-with-the-keycloak-integration


Instructions for playground were added in good faith but they are misleading. 
We going to remove them as I personally could not find a way to use **embeeded** playground with the server - but any other graphql client can be used if needed. 

https://github.com/aerogear/ionic-showcase/#using-the-graphql-playground-with-keycloak

**Comment by wtrocki** [comment]
Also if you looking for server examples only please refer to:
https://github.com/aerogear/keycloak-connect-graphql

Showcase is built only to demo the underlying angular app.

**Comment by cjohn001** [comment]
Hello,
maybe we have a different understanding of what is going wrong:

>> I have tried couple times instruction for running keycloak showcase server and showcase app (they are different app processes).
Please follow instructions here:
https://github.com/aerogear/ionic-showcase/#running-the-server-with-the-keycloak-integration

I followed the description .

>> (they are different app processes).
This is clear to me. As I have explained above, I just started mqtt, database, keycloak and the server. The console output mentions the playground link: http://localhost:4000/graphql
I tried with altair client. But seems like I have to get logged in  to keycloak before to get a jwt token.

>> https://github.com/aerogear/keycloak-connect-graphql
Thanks for the link.
>> Can you also recommend an example how I can login to keycloak within an ionic 4 capsule application using angular? This is actually what I was trying to do before I came over the issue.

**Comment by wtrocki** [comment]
Generally angular/ionic app should work. Please ignore information printed by server. Playground is not needed at all to run and interact with the angular app.

**Comment by cjohn001** [comment]
>>Generally angular/ionic app should work. Please ignore information printed by server. Playground is not needed at all to run and interact with the angular app.

Ok, for the server part I will look into the other example you linked.

One further note. I tried with altair client now. But with the script that is reference to get the keycloak jwt token also somethings seems to be wrong.

From docs:
Use `scripts/getToken.js` to get a valid header for the `developer` user.
The following script can be used to get a token for the default Keycloak credentials
node scripts/getToken.js

1. the script lies in scripts/keycloak/getToken.js
2. The script results in "err" but does not give me the bearer. I also trief with user passsword as parameters like described in the next section of the documentation.

**Comment by cjohn001** [comment]
Further note: I now tried to build the angular client. This used to work for me with older sources in the past. Now it also seems to have issues:

```
john@Morpheus ionic-showcase % npm run start

> ionic4-graphql-starter-app@1.0.0 start /Users/cjohn/Entwicklung/IMS_Help/ionic-showcase
> ionic serve

> ng run app:serve --host=0.0.0.0 --port=8100
[ng] Schema validation failed with the following errors:
[ng]   Data path ".builders['app-shell']" should have required property 'class'.

[ERROR] ng has unexpectedly closed (exit code 1).
        
        The Ionic CLI will exit. Please check any output above for error details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic4-graphql-starter-app@1.0.0 start: `ionic serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic4-graphql-starter-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cjohn/.npm/_logs/2020-01-26T19_33_33_073Z-debug.log
```

**Comment by darahayes** [comment]
@cjohn001 I've been mostly responsible for the Keycloak integration. I'm sorry you've had a frustrating experience. There were some recent changes for the underlying kecyloak init script and one of those accidental changes was to print out a more production ready server configuration (a Keycloak `bearer` client) which blocks access to the playground.

I've made a change in #296 to print out the configuration (`public` client) that will let you access the playground. Additionally, if you're looking for more straightforward and easier examples of adding Keycloak integration to a Node.js GraphQL server, I recommend you check out our repository for the [`keycloak-connect-graphql`](https://github.com/aerogear/keycloak-connect-graphql) and the examples folder within. Thanks!
