### ISSUE TITLE
Server should be written in typescript

### ISSUE THREAD

**Issue by wtrocki** [aerogear/ionic-showcase#41]
To enforce good patterns and add additional capabilities server side could be written in typescript

**Comment by supriyanta** [comment]
I want to work on this, assign me please....

**Comment by wtrocki** [comment]
I think that this issue will need to be checked with the wider team before we will move our server implementation.
We currently do not have any typescript usage so this issue is still needed, but I would love to send email to list first to get agreement on this matter with the wider group.
