### ISSUE TITLE
Only accepts mobile-services config, push-service

### ISSUE THREAD

**Issue by Klumze** [aerogear/ionic-showcase#94]
## Bug Report

* **Version/Commit**: 2.1.1
* **Ionic Version**: 4.10.3
* **Node.js / npm versions**: npm 6.8.0 Node.js 9.3.0

I believe this app should allow both the UPS config and the Mobile Services config and as it is sits right now, it is only allowing the config layout for Mobile Services. Also I believe that the way it is being done in the example (importing it using require) is circumventing some validation, because the example mobile-config.js file does not have the attribute `clusterName` in it but the example throws no errors. If you run the same code but simply define config as a variable rather than importing it using require, it will give you the error asking for the `clusterName` attribute. This is the best I can describe the issue, if there is anything else I can provide to try and make this issue easier to resolve please let me know and I will do my best to update this post with any additional info ASAP. 

Thank you in advance!

**Comment by wtrocki** [comment]
Yes. This is an issue related to our javascript SDK. Going to port that issue there.
